# Generated by Django 3.1.7 on 2021-04-21 23:35

import django.db.models.deletion
from django.db import migrations

import apps.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='project',
            field=apps.utils.fields.UUIDForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='attachmentcomment',
            name='instance',
            field=apps.utils.fields.UUIDForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.attachment'),
        ),
        migrations.AlterField(
            model_name='boardmessage',
            name='project',
            field=apps.utils.fields.UUIDForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='board_messages', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='boardmessagecomment',
            name='project',
            field=apps.utils.fields.UUIDForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='board_message_comments', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=apps.utils.fields.UUIDForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='instance',
            field=apps.utils.fields.UUIDForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.task'),
        ),
    ]
