# Generated by Django 3.0.5 on 2020-08-09 01:07

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Password"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Company name",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Company code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="User name"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Position"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Avatar"
                    ),
                ),
                (
                    "secret",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="secret"
                    ),
                ),
                (
                    "invitations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(
                            max_length=254, verbose_name="Email"
                        ),
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
