# Generated by Django 3.0.5 on 2020-07-16 22:44

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company name')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='User name')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='Position')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Avatar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
