# Generated by Django 3.0.5 on 2020-07-16 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='secret'),
        ),
    ]
