# Generated by Django 3.1.7 on 2021-03-28 14:59

from django.db import migrations

import apps.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210328_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company_code',
            field=apps.utils.fields.LowerCharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Company code'),
        ),
    ]
