# Generated by Django 3.0.5 on 2020-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_lead_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password'),
        ),
    ]
