# Generated by Django 3.1.7 on 2021-04-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210404_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
