# Generated by Django 3.1.7 on 2021-04-10 04:33

from django.db import migrations

import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('web', '0010_auto_20210410_0302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentry',
            options={'verbose_name': 'Blog Entries', 'verbose_name_plural': 'Blog Entries'},
        ),
        migrations.AddField(
            model_name='blogentry',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
