# Generated by Django 3.2 on 2021-05-22 19:04

from django.db import migrations

import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20210522_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from='name'),
        ),
    ]
