# Generated by Django 3.2 on 2021-05-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_blogcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Blog Categories'},
        ),
    ]
