# Generated by Django 3.2 on 2021-05-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_blogcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentrycontenttranslation',
            name='lang',
            field=models.CharField(choices=[('ES', 'Spanish')], db_index=True, max_length=2),
        ),
    ]
