# Generated by Django 3.2 on 2021-05-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_blogentrycontenttranslation_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='lang',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish')], default='EN', max_length=2),
        ),
        migrations.DeleteModel(
            name='BlogEntryContentTranslation',
        ),
    ]
