# Generated by Django 3.0.5 on 2020-04-24 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                (
                    'country',
                    django_countries.fields.CountryField(max_length=2),
                ),
                (
                    'name',
                    models.CharField(
                        db_index=True, max_length=50, verbose_name='name'
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        db_index=True, max_length=50, verbose_name='code'
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name='email',
                    ),
                ),
                (
                    'phone',
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name='phone',
                    ),
                ),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                (
                    'tree_id',
                    models.PositiveIntegerField(db_index=True, editable=False),
                ),
                ('level', models.PositiveIntegerField(editable=False)),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='areas',
                        to='core.Company',
                        verbose_name='company',
                    ),
                ),
                (
                    'parent',
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='children',
                        to='core.Area',
                    ),
                ),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('id', 'company')},
            },
        ),
    ]
