# Generated by Django 3.0.5 on 2020-06-18 01:17

from django.db import migrations


def create_main_company(apps, schema_editor):
    Company = apps.get_model("core", "Company")
    db_alias = schema_editor.connection.alias
    Company.objects.using(db_alias).create(
        country="CL",
        name="Adslab",
        code="adslab",
        email="viktor@adslab.io",
        phone="940560201",
    )


def reverse_create_main_company(apps, schema_editor):
    Company = apps.get_model("core", "Company")
    db_alias = schema_editor.connection.alias
    Company.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200618_0051'),
    ]

    operations = [
        migrations.RunPython(create_main_company, reverse_create_main_company),
    ]
