# Generated by Django 3.0.5 on 2021-01-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200809_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
    ]
