# Generated by Django 3.0.5 on 2020-04-28 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20200428_0111"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement", options={"ordering": ["-created"]},
        ),
        migrations.AlterUniqueTogether(
            name="announcement", unique_together={("id", "company")},
        ),
    ]
