# Generated by Django 3.0.5 on 2020-05-02 02:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200428_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
