# Generated by Django 3.0.5 on 2020-05-10 22:58

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_announcement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='logo', verbose_name='logo'),
        ),
    ]
