# Generated by Django 3.0.5 on 2020-06-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='code'),
        ),
    ]
