# Generated by Django 3.0.5 on 2020-04-28 01:04

import birthday.fields
import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20200428_0104"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="UserNotification", new_name="Notification",),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created"],
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("birthdays", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=birthday.fields.BirthdayField(default=datetime.date(2020, 4, 28)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="birthday_dayofyear_internal",
            field=models.PositiveSmallIntegerField(
                default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.Area",
            ),
        ),
    ]
