# Generated by Django 3.0.5 on 2020-07-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='icon_text',
            field=models.CharField(blank=True, max_length=20, verbose_name='icon text'),
        ),
    ]
