# Generated by Django 3.0.5 on 2020-04-28 03:24

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200428_0256"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", apps.users.models.UserManager()),],
        ),
    ]
