# Generated by Django 3.0.5 on 2020-08-08 22:54

import birthday.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200726_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=birthday.fields.BirthdayField(blank=True, null=True),
        ),
    ]
