# Generated by Django 3.0.5 on 2020-08-09 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("chat", "0002_auto_20200809_0107")]

    operations = [
        migrations.AlterModelOptions(name="room", options={"ordering": ["created"]})
    ]
