# Generated by Django 3.0.5 on 2020-11-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0003_auto_20200809_0405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
    ]
