# Generated by Django 3.0.5 on 2021-01-23 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0004_auto_20201101_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
    ]
