# Generated by Django 3.2 on 2021-05-20 04:03

from django.db import migrations, models

from ..models import chat_attachments_path


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_auto_20210131_0419"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageattachment",
            name="attachment",
            field=models.FileField(
                upload_to=chat_attachments_path, verbose_name="attachment"
            ),
        ),
    ]
