# Generated by Django 3.2 on 2021-06-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps.chat.context', '0011_auto_20210610_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
