# Generated by Django 3.2 on 2021-07-01 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20210328_1459'),
        ('apps.chat.context', '0012_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_message_ts',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='RoomUserRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_user_reads', to='core.company', verbose_name='company')),
                ('room', apps.utils.fields.UUIDForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='room_user_reads', to='chat.room', verbose_name='room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'user', 'room')},
            },
        ),
    ]
