# Generated by Django 3.2 on 2021-07-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20210701_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_message_ts',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
