# Generated by Django 3.2 on 2021-08-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_room_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='picture',
            new_name='image',
        ),
    ]
