# Generated by Django 3.2 on 2021-08-19 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0019_rename_picture_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_conversation',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is conversation'),
        ),
        migrations.AlterField(
            model_name='room',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL, verbose_name='admins'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_one_to_one',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is one to one'),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_message_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='outcasts',
            field=models.ManyToManyField(blank=True, related_name='outcats', to=settings.AUTH_USER_MODEL, verbose_name='outcats'),
        ),
        migrations.AlterField(
            model_name='room',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owners', to=settings.AUTH_USER_MODEL, verbose_name='owners'),
        ),
        migrations.AlterField(
            model_name='room',
            name='persistent',
            field=models.BooleanField(default=True, verbose_name='is persistent'),
        ),
    ]
