# Generated by Django 3.0.5 on 2020-08-09 01:09

from django.db import migrations


def create_base_company(apps, schema_editor):
    from ..models import Area, Company

    company1 = Company.objects.create(
        name="adslab", code="adslab", email="viktor@adslab.io"
    )
    company2 = Company.objects.create(
        name="firesoft", code="firesoft", email="viktor@firesoft.org"
    )
    Area.objects.create(name="default", company=company1)
    Area.objects.create(name="home", company=company2)


def reverse_create_company(apps, schema_editor):
    Company = apps.get_model("core", "company")
    Area = apps.get_model("core", "Area")
    db_alias = schema_editor.connection.alias

    Company.objects.using(db_alias).all().delete()
    Area.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [("core", "0002_auto_20200809_0107")]

    operations = [migrations.RunPython(create_base_company, reverse_create_company)]
