# Generated by Django 3.0.5 on 2020-08-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0003_create_default_company")]

    operations = [
        migrations.AlterField(
            model_name="area", name="name", field=models.CharField(max_length=50)
        )
    ]
