# Generated by Django 3.1.5 on 2021-01-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210123_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='state',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
