# Generated by Django 3.0.5 on 2020-08-09 01:07

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment', models.FileField(upload_to='', verbose_name='attachment')),
                ('mimetype', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mimetype')),
            ],
            options={
                'verbose_name': 'message attachment',
                'verbose_name_plural': 'message attachments',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('subject', models.CharField(blank=True, max_length=1024, null=True, verbose_name='subject')),
                ('max_users', models.IntegerField(default=0, verbose_name='Max users')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='password')),
                ('service_name', models.CharField(default='conference', max_length=255, verbose_name='Service Name')),
                ('is_public', models.BooleanField(default=True, verbose_name='is public')),
                ('persistent', models.BooleanField(default=True, verbose_name='is public')),
                ('any_can_invite', models.BooleanField(default=True, verbose_name='Any can invite')),
                ('members_only', models.BooleanField(default=False, verbose_name='members only')),
                ('is_one_to_one', models.BooleanField(default=False, verbose_name='is one to one')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
