# Generated by Django 3.0.5 on 2020-06-18 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_auto_20200618_0051'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='channel',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL, verbose_name='admins'),
        ),
        migrations.AddField(
            model_name='channel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.Company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.AddField(
            model_name='channel',
            name='outcasts',
            field=models.ManyToManyField(related_name='outcats', to=settings.AUTH_USER_MODEL, verbose_name='outcats'),
        ),
        migrations.AddField(
            model_name='channel',
            name='owners',
            field=models.ManyToManyField(related_name='owners', to=settings.AUTH_USER_MODEL, verbose_name='owners'),
        ),
        migrations.AlterUniqueTogether(
            name='messageattachment',
            unique_together={('id', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('id', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('name', 'company')},
        ),
    ]
