# Generated by Django 3.0.5 on 2020-06-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200618_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_one_to_one',
            field=models.BooleanField(default=False, verbose_name='is one to one'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='members_only',
            field=models.BooleanField(default=False, verbose_name='members only'),
        ),
    ]
