# Generated by Django 3.0.5 on 2020-07-26 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200618_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfConParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversationid', models.IntegerField()),
                ('joineddate', models.BigIntegerField()),
                ('leftdate', models.BigIntegerField(blank=True, null=True)),
                ('barejid', models.CharField(max_length=255)),
                ('jidresource', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ofconparticipant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfConversation',
            fields=[
                ('conversationid', models.IntegerField(primary_key=True, serialize=False)),
                ('room', models.CharField(blank=True, max_length=1024, null=True)),
                ('isexternal', models.SmallIntegerField()),
                ('startdate', models.BigIntegerField()),
                ('lastactivity', models.BigIntegerField()),
                ('messagecount', models.IntegerField()),
            ],
            options={
                'db_table': 'ofconversation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfExtComponentConf',
            fields=[
                ('subdomain', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('wildcard', models.IntegerField()),
                ('secret', models.CharField(blank=True, max_length=255, null=True)),
                ('permission', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ofextcomponentconf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfGroup',
            fields=[
                ('groupname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ofgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfGroupProp',
            fields=[
                ('groupname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('propvalue', models.TextField()),
            ],
            options={
                'db_table': 'ofgroupprop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfGroupUser',
            fields=[
                ('groupname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('administrator', models.IntegerField()),
            ],
            options={
                'db_table': 'ofgroupuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfId',
            fields=[
                ('idtype', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
            ],
            options={
                'db_table': 'ofid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfMessageArchive',
            fields=[
                ('messageid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('conversationid', models.IntegerField()),
                ('fromjid', models.CharField(max_length=1024)),
                ('fromjidresource', models.CharField(blank=True, max_length=1024, null=True)),
                ('tojid', models.CharField(max_length=1024)),
                ('tojidresource', models.CharField(blank=True, max_length=1024, null=True)),
                ('sentdate', models.BigIntegerField()),
                ('stanza', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ofmessagearchive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfmMucRoomProp',
            fields=[
                ('roomid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('propvalue', models.TextField()),
            ],
            options={
                'db_table': 'ofmucroomprop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfMucAffiliation',
            fields=[
                ('roomid', models.IntegerField(primary_key=True, serialize=False)),
                ('jid', models.CharField(max_length=1024)),
                ('affiliation', models.IntegerField()),
            ],
            options={
                'db_table': 'ofmucaffiliation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfMucConversationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.IntegerField()),
                ('messageid', models.IntegerField()),
                ('sender', models.CharField(max_length=1024)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('logtime', models.CharField(max_length=15)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('stanza', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ofmucconversationlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfMucMember',
            fields=[
                ('roomid', models.IntegerField(primary_key=True, serialize=False)),
                ('jid', models.CharField(max_length=1024)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('faqentry', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ofmucmember',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfMucRoom',
            fields=[
                ('serviceid', models.IntegerField(primary_key=True, serialize=False)),
                ('roomid', models.IntegerField()),
                ('creationdate', models.CharField(max_length=15)),
                ('modificationdate', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('naturalname', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('lockeddate', models.CharField(max_length=15)),
                ('emptydate', models.CharField(blank=True, max_length=15, null=True)),
                ('canchangesubject', models.IntegerField()),
                ('maxusers', models.IntegerField()),
                ('publicroom', models.IntegerField()),
                ('moderated', models.IntegerField()),
                ('membersonly', models.IntegerField()),
                ('caninvite', models.IntegerField()),
                ('roompassword', models.CharField(blank=True, max_length=50, null=True)),
                ('candiscoverjid', models.IntegerField()),
                ('logenabled', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('rolestobroadcast', models.IntegerField()),
                ('usereservednick', models.IntegerField()),
                ('canchangenick', models.IntegerField()),
                ('canregister', models.IntegerField()),
                ('allowpm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ofmucroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfMucService',
            fields=[
                ('serviceid', models.IntegerField()),
                ('subdomain', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ishidden', models.IntegerField()),
            ],
            options={
                'db_table': 'ofmucservice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfMucServiceProp',
            fields=[
                ('serviceid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('propvalue', models.TextField()),
            ],
            options={
                'db_table': 'ofmucserviceprop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfOffline',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('messageid', models.IntegerField()),
                ('creationdate', models.CharField(max_length=15)),
                ('messagesize', models.IntegerField()),
                ('stanza', models.TextField()),
            ],
            options={
                'db_table': 'ofoffline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfPresence',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('offlinepresence', models.TextField(blank=True, null=True)),
                ('offlinedate', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'ofpresence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfPrivacyList',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('isdefault', models.IntegerField()),
                ('list', models.TextField()),
            ],
            options={
                'db_table': 'ofprivacylist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfProperty',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('propvalue', models.CharField(max_length=4000)),
                ('encrypted', models.IntegerField(blank=True, null=True)),
                ('iv', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'ofproperty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfPubSubAffiliation',
            fields=[
                ('serviceid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nodeid', models.CharField(max_length=100)),
                ('jid', models.CharField(max_length=1024)),
                ('affiliation', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ofpubsubaffiliation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfPubSubDefaultConf',
            fields=[
                ('serviceid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('leaf', models.IntegerField()),
                ('deliverpayloads', models.IntegerField()),
                ('maxpayloadsize', models.IntegerField()),
                ('persistitems', models.IntegerField()),
                ('maxitems', models.IntegerField()),
                ('notifyconfigchanges', models.IntegerField()),
                ('notifydelete', models.IntegerField()),
                ('notifyretract', models.IntegerField()),
                ('presencebased', models.IntegerField()),
                ('senditemsubscribe', models.IntegerField()),
                ('publishermodel', models.CharField(max_length=15)),
                ('subscriptionenabled', models.IntegerField()),
                ('accessmodel', models.CharField(max_length=10)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('replypolicy', models.CharField(blank=True, max_length=15, null=True)),
                ('associationpolicy', models.CharField(max_length=15)),
                ('maxleafnodes', models.IntegerField()),
            ],
            options={
                'db_table': 'ofpubsubdefaultconf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfPubSubitem',
            fields=[
                ('serviceid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nodeid', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100)),
                ('jid', models.CharField(max_length=1024)),
                ('creationdate', models.CharField(max_length=15)),
                ('payload', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ofpubsubitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfPubSubNode',
            fields=[
                ('serviceid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nodeid', models.CharField(max_length=100)),
                ('leaf', models.IntegerField()),
                ('creationdate', models.CharField(max_length=15)),
                ('modificationdate', models.CharField(max_length=15)),
                ('parent', models.CharField(blank=True, max_length=100, null=True)),
                ('deliverpayloads', models.IntegerField()),
                ('maxpayloadsize', models.IntegerField(blank=True, null=True)),
                ('persistitems', models.IntegerField(blank=True, null=True)),
                ('maxitems', models.IntegerField(blank=True, null=True)),
                ('notifyconfigchanges', models.IntegerField()),
                ('notifydelete', models.IntegerField()),
                ('notifyretract', models.IntegerField()),
                ('presencebased', models.IntegerField()),
                ('senditemsubscribe', models.IntegerField()),
                ('publishermodel', models.CharField(max_length=15)),
                ('subscriptionenabled', models.IntegerField()),
                ('configsubscription', models.IntegerField()),
                ('accessmodel', models.CharField(max_length=10)),
                ('payloadtype', models.CharField(blank=True, max_length=100, null=True)),
                ('bodyxslt', models.CharField(blank=True, max_length=100, null=True)),
                ('dataformxslt', models.CharField(blank=True, max_length=100, null=True)),
                ('creator', models.CharField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('replypolicy', models.CharField(blank=True, max_length=15, null=True)),
                ('associationpolicy', models.CharField(blank=True, max_length=15, null=True)),
                ('maxleafnodes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ofpubsubnode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfPubSubNodeGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceid', models.CharField(max_length=100)),
                ('nodeid', models.CharField(max_length=100)),
                ('rostergroup', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ofpubsubnodegroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfPubSubNodeJids',
            fields=[
                ('serviceid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nodeid', models.CharField(max_length=100)),
                ('jid', models.CharField(max_length=1024)),
                ('associationtype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ofpubsubnodejids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfPubSubSubscription',
            fields=[
                ('serviceid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nodeid', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100)),
                ('jid', models.CharField(max_length=1024)),
                ('owner', models.CharField(max_length=1024)),
                ('state', models.CharField(max_length=15)),
                ('deliver', models.IntegerField()),
                ('digest', models.IntegerField()),
                ('digest_frequency', models.IntegerField()),
                ('expire', models.CharField(blank=True, max_length=15, null=True)),
                ('includebody', models.IntegerField()),
                ('showvalues', models.CharField(max_length=30)),
                ('subscriptiontype', models.CharField(max_length=10)),
                ('subscriptiondepth', models.IntegerField()),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'ofpubsubsubscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfRemoteServerConf',
            fields=[
                ('xmppdomain', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('remoteport', models.IntegerField(blank=True, null=True)),
                ('permission', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ofremoteserverconf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfRoster',
            fields=[
                ('rosterid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('jid', models.CharField(max_length=1024)),
                ('sub', models.IntegerField()),
                ('ask', models.IntegerField()),
                ('recv', models.IntegerField()),
                ('nick', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ofroster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfRrds',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('updateddate', models.BigIntegerField()),
                ('bytes', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ofrrds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfSaslAuthorized',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('principal', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'ofsaslauthorized',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfSecurityAuditlog',
            fields=[
                ('msgid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('entrystamp', models.BigIntegerField()),
                ('summary', models.CharField(max_length=255)),
                ('node', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ofsecurityauditlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfUser',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('storedkey', models.CharField(blank=True, max_length=32, null=True)),
                ('serverkey', models.CharField(blank=True, max_length=32, null=True)),
                ('salt', models.CharField(blank=True, max_length=32, null=True)),
                ('iterations', models.IntegerField(blank=True, null=True)),
                ('plainpassword', models.CharField(blank=True, max_length=32, null=True)),
                ('encryptedpassword', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('creationdate', models.CharField(max_length=15)),
                ('modificationdate', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'ofuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfUserFlag',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('starttime', models.CharField(blank=True, max_length=15, null=True)),
                ('endtime', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'ofuserflag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfUserProp',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('propvalue', models.TextField()),
            ],
            options={
                'db_table': 'ofuserprop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfVCard',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('vcard', models.TextField()),
            ],
            options={
                'db_table': 'ofvcard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfVersion',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'ofversion',
                'managed': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='message',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='message',
            name='company',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='messageattachment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='message',
        ),
        migrations.CreateModel(
            name='OfRosterGroups',
            fields=[
                ('rosterid', models.OneToOneField(db_column='rosterid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='chat.OfRoster')),
                ('rank', models.IntegerField()),
                ('groupname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ofrostergroups',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
    ]
