# Generated by Django 3.0.5 on 2020-08-08 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_messageattachment_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='channel',
            new_name='room',
        ),
    ]
