# Generated by Django 3.2 on 2021-05-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210328_1459'),
        ('chat', '0007_alter_messageattachment_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='messageattachment',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('uuid', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='messageattachment',
            unique_together={('uuid', 'company')},
        ),
    ]
