# Generated by Django 3.2 on 2021-06-01 03:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import django_extensions.db.fields
import model_utils.fields
import uuid

import apps.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20210328_1459'),
        ('chat', '0009_auto_20210523_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='message',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.CreateModel(
            name='RoomRead',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reads', to='core.company', verbose_name='company')),
                ('room', apps.utils.fields.UUIDForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='chat.room', verbose_name='room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'room read',
                'verbose_name_plural': 'room reads',
                'unique_together': {('uuid', 'company', 'room', 'user')},
            },
        ),
    ]
